### ISSUE TITLE
Self hosting?

### ISSUE THREAD

**Issue by matan129** [datamechanics/delight#26]
Hi,

First of all, I just wanted to say that the UI looks really great!

I know that as the README says, the backend component is current closed source. Are there any plans to open source it so it could be self hosted?

Thanks,
Matan

**Comment by lower19** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by phyyou** [comment]
Any updates?

**Comment by lower19** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by phyyou** [comment]
It was automated? I want to see maintainer...

**Comment by ImpSy** [comment]
Hello,

Sorry for taking so long to answer but unfortunately self hosting will not be possible at the moment
The ingestion pipeline is too deeply related to our paid product [Ocean for Apache Spark](https://spot.io/products/ocean-apache-spark/) for being released publicly

I'm sorry if it's not the answer you were looking for
