### ISSUE TITLE
No metrics shown for pipeline runs on Databricks

### ISSUE THREAD

**Issue by Selbstsesslingen** [datamechanics/delight#28]
**Describe the bug**
Pipeline runs on Databricks with [runtime 10.4](https://docs.databricks.com/release-notes/runtime/10.4.html) (Spark 3.2.1) show up in the dashboard with the correct job name, number of nodes and available memory. But there are no metrics shown. The historical Spark UI does also not show any jobs or stages. It only shows when the executors were added.
The pipeline however finished successful and Databricks' Spark UI shows correctly the stages and metrics.

**To Reproduce**
1. Take the [init-script from delight's git repo](https://github.com/datamechanics/delight/blob/main/documentation/databricks.md), adapt it and upload it to dbfs 
2. Add the init-script to any databricks workflow's job cluster (cluster scoped init script)
3. Start a run of the workflow
4. Find rather empty Delight Dashboard

**Expected behavior**
Find informative Delight Dashboard

**Screenshots**
![overview](https://user-images.githubusercontent.com/63634601/201101375-55a90ae0-a93f-4945-a2b6-381b602e161c.png)

![details](https://user-images.githubusercontent.com/63634601/201101644-c39ad67c-34e2-4e36-bc8e-e514520d474f.png)

**Context**
- Platform: Databricks
- Platform version: 10.4 LTS
- Spark version: Databricks Spark 3.2.1
- Scala version: 2.12
- Delight version: delight-0-38-0

**Comment by lower19** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
