### ISSUE TITLE
Support for newer versions of Spark?

### ISSUE THREAD

**Issue by tsbriggs02** [datamechanics/delight#34]
My company is currently using Pyspark 3.3.0.  Delight looks awesome and I'd like to convince my company to use it, but the [documentation](https://github.com/datamechanics/delight) says that "Delight is compatible with Spark 2.4.0 to Spark 3.1.1."

I'd like it if Delight could be made compatible with the Pyspark 3.3.x versions.

More generally, the last commit to the repo is from Sept. 2022 -- is Delight still being actively developed?

**Comment by ImpSy** [comment]
Hello,

Sorry for the late response, Delight already support spark 3.3 (even though it's not stated in the readme)
The [latest commit](https://github.com/datamechanics/delight/blob/main/justfile#L115) was actually to add tests for spark 3.3.0

As for the state of Delight, the project is currently working on auto-pilot but we respond to support request coming through the app
